# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_category_add(object):
    def setupUi(self, category_add):
        category_add.setObjectName("category_add")
        category_add.resize(383, 287)
        self.category_add_add_button = QtWidgets.QPushButton(category_add)
        self.category_add_add_button.setGeometry(QtCore.QRect(280, 20, 91, 51))
        self.category_add_add_button.setObjectName("category_add_add_button")
        self.category_add_list_view = QtWidgets.QListView(category_add)
        self.category_add_list_view.setGeometry(QtCore.QRect(10, 80, 261, 192))
        self.category_add_list_view.setObjectName("category_add_list_view")
        self.category_add_delete_button = QtWidgets.QPushButton(category_add)
        self.category_add_delete_button.setGeometry(QtCore.QRect(280, 80, 91, 51))
        self.category_add_delete_button.setObjectName("category_add_delete_button")
        self.category_add_text_box = QtWidgets.QLineEdit(category_add)
        self.category_add_text_box.setGeometry(QtCore.QRect(10, 20, 261, 51))
        self.category_add_text_box.setObjectName("category_add_text_box")
        self.category_add_exit_button = QtWidgets.QPushButton(category_add)
        self.category_add_exit_button.setGeometry(QtCore.QRect(280, 220, 91, 51))
        self.category_add_exit_button.setObjectName("category_add_exit_button")

        self.retranslateUi(category_add)
        self.category_add_add_button.clicked.connect(category_add.on_clicked_add) # type: ignore
        self.category_add_delete_button.clicked.connect(category_add.on_clicked_delete) # type: ignore
        self.category_add_exit_button.clicked.connect(category_add.on_clicked_quit) # type: ignore
        self.category_add_list_view.clicked['QModelIndex'].connect(category_add.on_clicked_list_view_index) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(category_add)

    def retranslateUi(self, category_add):
        _translate = QtCore.QCoreApplication.translate
        category_add.setWindowTitle(_translate("category_add", "category_add"))
        self.category_add_add_button.setText(_translate("category_add", "추가"))
        self.category_add_delete_button.setText(_translate("category_add", "삭제"))
        self.category_add_exit_button.setText(_translate("category_add", "종료"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    category_add = QtWidgets.QWidget()
    ui = Ui_category_add()
    ui.setupUi(category_add)
    category_add.show()
    sys.exit(app.exec_())
