# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1080, 720)
        self.input = QtWidgets.QGroupBox(Dialog)
        self.input.setGeometry(QtCore.QRect(364, 264, 372, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input.setObjectName("input")
        self.input_button = QtWidgets.QPushButton(self.input)
        self.input_button.setGeometry(QtCore.QRect(110, 140, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_button.sizePolicy().hasHeightForWidth())
        self.input_button.setSizePolicy(sizePolicy)
        self.input_button.setObjectName("input_button")
        self.lineEdit = QtWidgets.QLineEdit(self.input)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.input)
        self.label.setGeometry(QtCore.QRect(310, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.input)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 331, 81))
        font = QtGui.QFont()
        font.setFamily("함초롬돋움")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.output = QtWidgets.QGroupBox(Dialog)
        self.output.setGeometry(QtCore.QRect(364, 264, 372, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        self.input_button_2 = QtWidgets.QPushButton(self.output)
        self.input_button_2.setGeometry(QtCore.QRect(110, 140, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_button_2.sizePolicy().hasHeightForWidth())
        self.input_button_2.setSizePolicy(sizePolicy)
        self.input_button_2.setObjectName("input_button_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.output)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 80, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.output)
        self.label_3.setGeometry(QtCore.QRect(310, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.output)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 331, 81))
        font = QtGui.QFont()
        font.setFamily("함초롬돋움")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.input.setTitle(_translate("Dialog", "입금 그룹"))
        self.input_button.setText(_translate("Dialog", "버튼을 눌러 입금"))
        self.label.setText(_translate("Dialog", "원"))
        self.label_2.setText(_translate("Dialog", "금액을 입력해주세요"))
        self.output.setTitle(_translate("Dialog", "출금 그룹"))
        self.input_button_2.setText(_translate("Dialog", "버튼을 눌러 출금"))
        self.label_3.setText(_translate("Dialog", "원"))
        self.label_4.setText(_translate("Dialog", "금액을 입력해주세요"))

    def on_clicked_input(self):
        return
    def on_clicked_output(self):
        return


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
